openapi: 3.0.3
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: "1.0"
servers:
- url: http://localhost:80
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        allowEmptyValue: true
        schema:
          type: string
          description: View to render
          example: full
          enum:
          - default
          - full
        example: default
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/TrackedAccountResponseFullCollection'
                $ref: '#/components/schemas/TrackedAccountCollection'
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Sed ut.:
                    amount: 5634291384550134497
                    asset: 202586210
                    decimals: 891370476552451481
                    metadataHash: Non quisquam tempore ex blanditiis.
                    name: Id necessitatibus ut unde.
                    unitName: Illo totam facere suscipit magni molestiae.
                    url: Cupiditate totam eum expedita ut illum.
                round: 11826018997914015028
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Sed ut.:
                    amount: 5634291384550134497
                    asset: 202586210
                    decimals: 891370476552451481
                    metadataHash: Non quisquam tempore ex blanditiis.
                    name: Id necessitatibus ut unde.
                    unitName: Illo totam facere suscipit magni molestiae.
                    url: Cupiditate totam eum expedita ut illum.
                round: 11826018997914015028
    post:
      tags:
      - account
      summary: add account
      description: Add Algorand account(s) to track
      operationId: account#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      responses:
        "200":
          description: OK response.
  /account/{address}:
    delete:
      tags:
      - account
      summary: delete account
      description: Delete Algorand account(s) to track
      operationId: account#delete
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: array
          items:
            type: string
            example: Eaque dolor reiciendis suscipit consequatur qui.
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
        example:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      responses:
        "200":
          description: OK response.
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        schema:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              example:
                address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Id aliquid molestiae similique id.:
                    amount: 3059485608281045639
                    asset: 202586210
                    decimals: 14323982702047730233
                    metadataHash: Explicabo eos.
                    name: Accusamus maxime.
                    unitName: Veritatis ipsum quis ex laborum.
                    url: Natus non et earum quia.
                round: 7528826264469965543
  /account/iswatched:
    post:
      tags:
      - account
      summary: iswatched account
      description: Returns which of the passed accounts are currently being monitored
      operationId: account#iswatched
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Magnam sint dolorum debitis repellat et.
                example:
                - Numquam mollitia nihil rerum a veritatis.
                - Suscipit quo.
              example:
              - Soluta minima.
              - Tempore nulla tempora sit nemo.
              - Vel ullam quisquam sit.
  /inspect/unpack:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded) returning 'goal clerk inspect'
        output
      operationId: inspect#unpack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnpackRequestBody'
            example:
              msgpack: Temporibus est voluptate quam dolores et.
      responses:
        "200":
          description: OK response.
          content:
            text/plain:
              schema:
                type: string
                description: Returns output from goal clerk inspect of passed msgpack-encoded
                  payload
                example: Qui et beatae voluptate dolore accusantium itaque.
              example: Adipisci quibusdam alias aliquid cupiditate eum ab.
  /live:
    get:
      tags:
      - info
      summary: live info
      description: Simple health check
      operationId: info#live
      responses:
        "200":
          description: OK response.
  /openapi3.yaml:
    get:
      tags:
      - info
      summary: Download ./openapi3.yaml
      operationId: info#/openapi3.yaml
      responses:
        "200":
          description: File downloaded
  /version:
    get:
      tags:
      - info
      summary: version info
      description: Returns version information for the service
      operationId: info#version
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: 14193a3-dirty
              example: 14193a3-dirty
components:
  schemas:
    Account:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Deserunt accusantium.:
              amount: 3059485608281045639
              asset: 202586210
              decimals: 14323982702047730233
              metadataHash: Explicabo eos.
              name: Accusamus maxime.
              unitName: Veritatis ipsum quis ex laborum.
              url: Natus non et earum quia.
            Itaque explicabo.:
              amount: 3059485608281045639
              asset: 202586210
              decimals: 14323982702047730233
              metadataHash: Explicabo eos.
              name: Accusamus maxime.
              unitName: Veritatis ipsum quis ex laborum.
              url: Natus non et earum quia.
            Omnis expedita omnis eligendi totam dignissimos consectetur.:
              amount: 3059485608281045639
              asset: 202586210
              decimals: 14323982702047730233
              metadataHash: Explicabo eos.
              name: Accusamus maxime.
              unitName: Veritatis ipsum quis ex laborum.
              url: Natus non et earum quia.
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 4897950650108277391
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Maxime voluptatem.:
            amount: 3059485608281045639
            asset: 202586210
            decimals: 14323982702047730233
            metadataHash: Explicabo eos.
            name: Accusamus maxime.
            unitName: Veritatis ipsum quis ex laborum.
            url: Natus non et earum quia.
        round: 7561589628655474940
      required:
      - address
      - round
      - holdings
    AddRequestBody:
      type: object
      properties:
        address:
          type: array
          items:
            type: string
            example: Consectetur nisi qui ipsa dolor.
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      example:
        address:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      required:
      - address
    AlgodexAccount:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Odio dolor aut provident accusantium.:
              amount: 17866778959212843392
              asset: 202586210
              decimals: 27042102648704077
              metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
              name: Nesciunt aperiam incidunt iusto id assumenda est.
              unitName: Dignissimos explicabo in aut.
              url: Est accusantium quia magnam eos.
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 312247509368492821
      description: A TrackedAccount is an Account returned by the indexer
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Et pariatur tenetur dolor facilis ut.:
            amount: 17866778959212843392
            asset: 202586210
            decimals: 27042102648704077
            metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
            name: Nesciunt aperiam incidunt iusto id assumenda est.
            unitName: Dignissimos explicabo in aut.
            url: Est accusantium quia magnam eos.
        round: 13614267304217243986
      required:
      - address
      - round
      - holdings
    TrackedAccountCollection:
      type: array
      items:
        $ref: '#/components/schemas/AlgodexAccount'
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Sed ut.:
            amount: 5634291384550134497
            asset: 202586210
            decimals: 891370476552451481
            metadataHash: Non quisquam tempore ex blanditiis.
            name: Id necessitatibus ut unde.
            unitName: Illo totam facere suscipit magni molestiae.
            url: Cupiditate totam eum expedita ut illum.
        round: 11826018997914015028
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Sed ut.:
            amount: 5634291384550134497
            asset: 202586210
            decimals: 891370476552451481
            metadataHash: Non quisquam tempore ex blanditiis.
            name: Id necessitatibus ut unde.
            unitName: Illo totam facere suscipit magni molestiae.
            url: Cupiditate totam eum expedita ut illum.
        round: 11826018997914015028
    TrackedAccountResponseFull:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Dolor delectus est.:
              amount: 17866778959212843392
              asset: 202586210
              decimals: 27042102648704077
              metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
              name: Nesciunt aperiam incidunt iusto id assumenda est.
              unitName: Dignissimos explicabo in aut.
              url: Est accusantium quia magnam eos.
          additionalProperties: true
        round:
          type: integer
          description: Round fetched
          example: 15375360478765913623
      description: A TrackedAccount is an Account returned by the indexer (full view)
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Quod nihil.:
            amount: 17866778959212843392
            asset: 202586210
            decimals: 27042102648704077
            metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
            name: Nesciunt aperiam incidunt iusto id assumenda est.
            unitName: Dignissimos explicabo in aut.
            url: Est accusantium quia magnam eos.
        round: 2504894343791819567
      required:
      - address
      - round
      - holdings
    TrackedAccountResponseFullCollection:
      type: array
      items:
        $ref: '#/components/schemas/TrackedAccountResponseFull'
      description: ListResponseBody is the result type for an array of TrackedAccountResponse
        (full view)
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Quia perspiciatis deserunt reiciendis ut mollitia nemo.:
            amount: 17866778959212843392
            asset: 202586210
            decimals: 27042102648704077
            metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
            name: Nesciunt aperiam incidunt iusto id assumenda est.
            unitName: Dignissimos explicabo in aut.
            url: Est accusantium quia magnam eos.
        round: 1439603630392093503
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Quia perspiciatis deserunt reiciendis ut mollitia nemo.:
            amount: 17866778959212843392
            asset: 202586210
            decimals: 27042102648704077
            metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
            name: Nesciunt aperiam incidunt iusto id assumenda est.
            unitName: Dignissimos explicabo in aut.
            url: Est accusantium quia magnam eos.
        round: 1439603630392093503
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Quia perspiciatis deserunt reiciendis ut mollitia nemo.:
            amount: 17866778959212843392
            asset: 202586210
            decimals: 27042102648704077
            metadataHash: Ullam dignissimos id soluta nesciunt voluptatibus.
            name: Nesciunt aperiam incidunt iusto id assumenda est.
            unitName: Dignissimos explicabo in aut.
            url: Est accusantium quia magnam eos.
        round: 1439603630392093503
    UnpackRequestBody:
      type: object
      properties:
        msgpack:
          type: string
          example: Voluptatem aliquam impedit culpa.
      example:
        msgpack: Rem enim est.
tags:
- name: info
  description: The info service provides information on version data, liveness, readiness
    checks, etc.
- name: account
  description: The account service specifies which Algorand accounts to track
- name: inspect
  description: The inspect service provides msgpack decoding services
