openapi: 3.0.3
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        allowEmptyValue: true
        schema:
          type: string
          description: View to render
          example: full
          enum:
          - default
          - full
        example: full
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/TrackedAccountResponseFullCollection'
                $ref: '#/components/schemas/TrackedAccountCollection'
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Id vitae nulla sunt exercitationem.:
                    amount: 14649371533185185085
                    asset: 202586210
                    decimals: 13557633239838944818
                    metadataHash: Tempore ex blanditiis aut.
                    name: Necessitatibus ut unde soluta illo.
                    unitName: Facere suscipit magni molestiae soluta cupiditate totam.
                    url: Expedita ut illum aperiam.
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Id vitae nulla sunt exercitationem.:
                    amount: 14649371533185185085
                    asset: 202586210
                    decimals: 13557633239838944818
                    metadataHash: Tempore ex blanditiis aut.
                    name: Necessitatibus ut unde soluta illo.
                    unitName: Facere suscipit magni molestiae soluta cupiditate totam.
                    url: Expedita ut illum aperiam.
    post:
      tags:
      - account
      summary: add account
      description: Add Algorand account(s) to track
      operationId: account#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              address:
              - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
              - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      responses:
        "200":
          description: OK response.
  /account/{address}:
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        schema:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              example:
                address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  Laborum laboriosam natus non et earum.:
                    amount: 12373123001069819448
                    asset: 202586210
                    decimals: 5519094376750021556
                    metadataHash: Saepe reiciendis molestiae labore.
                    name: Et velit labore laborum rerum dolores.
                    unitName: Blanditiis ut ea est esse.
                    url: Blanditiis quaerat nihil repellendus explicabo eos.
                  Maxime accusamus veritatis ipsum quis.:
                    amount: 12373123001069819448
                    asset: 202586210
                    decimals: 5519094376750021556
                    metadataHash: Saepe reiciendis molestiae labore.
                    name: Et velit labore laborum rerum dolores.
                    unitName: Blanditiis ut ea est esse.
                    url: Blanditiis quaerat nihil repellendus explicabo eos.
  /inspect/unpack:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded) returning 'goal clerk inspect'
        output
      operationId: inspect#unpack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnpackRequestBody'
            example:
              msgpack: Id assumenda.
      responses:
        "200":
          description: OK response.
          content:
            text/plain:
              schema:
                type: string
                description: Returns output from goal clerk inspect of passed msgpack-encoded
                  payload
                example: Qui est maxime voluptatem eaque cum.
              example: Aut provident accusantium itaque doloribus voluptatem et.
  /live:
    get:
      tags:
      - info
      summary: live info
      description: Simple health check
      operationId: info#live
      responses:
        "200":
          description: OK response.
  /openapi.json:
    get:
      tags:
      - account
      summary: Download ./gen/http/openapi.json
      operationId: account#/openapi.json
      responses:
        "200":
          description: File downloaded
  /version:
    get:
      tags:
      - info
      summary: version info
      description: Returns version information for the service
      operationId: info#version
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: 14193a3-dirty
              example: 14193a3-dirty
components:
  schemas:
    Account:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Est voluptate quam dolores et voluptatibus.:
              amount: 12373123001069819448
              asset: 202586210
              decimals: 5519094376750021556
              metadataHash: Saepe reiciendis molestiae labore.
              name: Et velit labore laborum rerum dolores.
              unitName: Blanditiis ut ea est esse.
              url: Blanditiis quaerat nihil repellendus explicabo eos.
          additionalProperties: true
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Dolorem quia omnis ut.:
            amount: 12373123001069819448
            asset: 202586210
            decimals: 5519094376750021556
            metadataHash: Saepe reiciendis molestiae labore.
            name: Et velit labore laborum rerum dolores.
            unitName: Blanditiis ut ea est esse.
            url: Blanditiis quaerat nihil repellendus explicabo eos.
          Voluptate quia iste quis.:
            amount: 12373123001069819448
            asset: 202586210
            decimals: 5519094376750021556
            metadataHash: Saepe reiciendis molestiae labore.
            name: Et velit labore laborum rerum dolores.
            unitName: Blanditiis ut ea est esse.
            url: Blanditiis quaerat nihil repellendus explicabo eos.
      required:
      - address
      - holdings
    AddRequestBody:
      type: object
      properties:
        address:
          type: array
          items:
            type: string
            example: Voluptate facilis possimus ut.
          example:
          - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      example:
        address:
        - 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        - 6APKHESCBZIAAZBMMZYW3MEHWYBIT3V7XDA2MF45J5TUZG5LXFXFVBJSFY
      required:
      - address
    AlgodexAccount:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Ut alias voluptatum voluptas voluptatem officia.:
              amount: 9526786926685192104
              asset: 202586210
              decimals: 955764664882562990
              metadataHash: Commodi enim quia.
              name: Deserunt reiciendis ut mollitia nemo.
              unitName: Et dolorem ullam dignissimos id soluta nesciunt.
              url: Voluptatem nesciunt aperiam.
          additionalProperties: true
      description: A TrackedAccount is an Account returned by the indexer
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Explicabo occaecati.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
          Harum quia.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
          In velit.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
      required:
      - address
      - holdings
    TrackedAccountCollection:
      type: array
      items:
        $ref: '#/components/schemas/AlgodexAccount'
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Id vitae nulla sunt exercitationem.:
            amount: 14649371533185185085
            asset: 202586210
            decimals: 13557633239838944818
            metadataHash: Tempore ex blanditiis aut.
            name: Necessitatibus ut unde soluta illo.
            unitName: Facere suscipit magni molestiae soluta cupiditate totam.
            url: Expedita ut illum aperiam.
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Id vitae nulla sunt exercitationem.:
            amount: 14649371533185185085
            asset: 202586210
            decimals: 13557633239838944818
            metadataHash: Tempore ex blanditiis aut.
            name: Necessitatibus ut unde soluta illo.
            unitName: Facere suscipit magni molestiae soluta cupiditate totam.
            url: Expedita ut illum aperiam.
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Id vitae nulla sunt exercitationem.:
            amount: 14649371533185185085
            asset: 202586210
            decimals: 13557633239838944818
            metadataHash: Tempore ex blanditiis aut.
            name: Necessitatibus ut unde soluta illo.
            unitName: Facere suscipit magni molestiae soluta cupiditate totam.
            url: Expedita ut illum aperiam.
    TrackedAccountResponseFull:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Account Assets
          example:
            Aut occaecati optio voluptatem saepe.:
              amount: 9526786926685192104
              asset: 202586210
              decimals: 955764664882562990
              metadataHash: Commodi enim quia.
              name: Deserunt reiciendis ut mollitia nemo.
              unitName: Et dolorem ullam dignissimos id soluta nesciunt.
              url: Voluptatem nesciunt aperiam.
            Explicabo dolorum.:
              amount: 9526786926685192104
              asset: 202586210
              decimals: 955764664882562990
              metadataHash: Commodi enim quia.
              name: Deserunt reiciendis ut mollitia nemo.
              unitName: Et dolorem ullam dignissimos id soluta nesciunt.
              url: Voluptatem nesciunt aperiam.
            Odio dolores minima aliquid.:
              amount: 9526786926685192104
              asset: 202586210
              decimals: 955764664882562990
              metadataHash: Commodi enim quia.
              name: Deserunt reiciendis ut mollitia nemo.
              unitName: Et dolorem ullam dignissimos id soluta nesciunt.
              url: Voluptatem nesciunt aperiam.
          additionalProperties: true
      description: A TrackedAccount is an Account returned by the indexer (full view)
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Dolor in delectus.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
          Modi enim optio minus explicabo aut labore.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
          Sit ut dolore aspernatur consectetur nisi qui.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
      required:
      - address
      - holdings
    TrackedAccountResponseFullCollection:
      type: array
      items:
        $ref: '#/components/schemas/TrackedAccountResponseFull'
      description: ListResponseBody is the result type for an array of TrackedAccountResponse
        (full view)
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Id aliquid molestiae similique id.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          Id aliquid molestiae similique id.:
            amount: 9526786926685192104
            asset: 202586210
            decimals: 955764664882562990
            metadataHash: Commodi enim quia.
            name: Deserunt reiciendis ut mollitia nemo.
            unitName: Et dolorem ullam dignissimos id soluta nesciunt.
            url: Voluptatem nesciunt aperiam.
    UnpackRequestBody:
      type: object
      properties:
        msgpack:
          type: string
          example: Accusantium quidem omnis expedita omnis.
      example:
        msgpack: Totam dignissimos consectetur ratione itaque explicabo.
tags:
- name: account
  description: The account service specifies which Algorand accounts to track
- name: inspect
  description: The inspect service provides msgpack decoding services
- name: info
  description: The info service provides information on version data, liveness, readiness
    checks, etc.
