openapi: 3.0.3
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        allowEmptyValue: true
        schema:
          type: string
          description: View to render
          example: default
          enum:
          - default
          - full
        example: full
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/TrackedAccountResponseFullCollection'
                $ref: '#/components/schemas/TrackedAccountCollection'
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  "202586210": 100
                  "205471981": 200
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  "202586210": 100
                  "205471981": 200
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  "202586210": 100
                  "205471981": 200
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  "202586210": 100
                  "205471981": 200
  /account/{address}:
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        schema:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              example:
                address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                holdings:
                  "202586210": 100
                  "205471981": 200
    put:
      tags:
      - account
      summary: add account
      description: Add Algorand account to track
      operationId: account#add
      parameters:
      - name: address
        in: path
        required: true
        schema:
          type: string
          example: Saepe reiciendis molestiae labore.
        example: Et velit labore laborum rerum dolores.
      responses:
        "200":
          description: OK response.
  /inspect:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded)
      operationId: inspect#unpack
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnpackRequestBody'
            example:
              msgpack: Aperiam reiciendis id aut.
      responses:
        "200":
          description: OK response.
  /openapi.json:
    get:
      tags:
      - account
      summary: Download ./gen/http/openapi.json
      operationId: account#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Account:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Opted-in ASA IDs
          example:
            "202586210": 100
            "205471981": 200
          additionalProperties: true
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
      required:
      - address
      - holdings
    AlgodexAccount:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Opted-in ASA IDs
          example:
            "202586210": 100
            "205471981": 200
          additionalProperties: true
      description: A TrackedAccount is an Account returned by the indexer
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
      required:
      - address
      - holdings
    TrackedAccountCollection:
      type: array
      items:
        $ref: '#/components/schemas/AlgodexAccount'
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
    TrackedAccountResponseFull:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        holdings:
          type: object
          description: Opted-in ASA IDs
          example:
            "202586210": 100
            "205471981": 200
          additionalProperties: true
      description: A TrackedAccount is an Account returned by the indexer (full view)
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
      required:
      - address
      - holdings
    TrackedAccountResponseFullCollection:
      type: array
      items:
        $ref: '#/components/schemas/TrackedAccountResponseFull'
      description: ListResponseBody is the result type for an array of TrackedAccountResponse
        (full view)
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        holdings:
          "202586210": 100
          "205471981": 200
    UnpackRequestBody:
      type: object
      properties:
        msgpack:
          type: string
          example: Repellat dolorem quia ut repellendus sit sunt.
      example:
        msgpack: Sunt eaque maiores.
tags:
- name: account
  description: The account service specifies which Algorand accounts to track
- name: inspect
  description: The inspect service provides msgpack decoding services
