swagger: "2.0"
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Holdings
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /account:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        required: false
        type: string
        enum:
        - default
        - full
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountTrackedAccountResponseCollection'
      schemes:
      - http
  /account/{address}:
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        type: string
        maxLength: 58
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetResponseBody'
            required:
            - address
            - holdings
      schemes:
      - http
    put:
      tags:
      - account
      summary: add account
      description: Add Algorand account to track
      operationId: account#add
      parameters:
      - name: address
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /inspect:
    post:
      tags:
      - inspect
      summary: unpack inspect
      description: Unpack a msgpack body (base64 encoded)
      operationId: inspect#unpack
      parameters:
      - name: UnpackRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/InspectUnpackRequestBody'
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - account
      summary: Download ./gen/http/openapi.json
      operationId: account#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  AccountGetResponseBody:
    title: AccountGetResponseBody
    type: object
    properties:
      address:
        type: string
        description: Public Account address
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        maxLength: 58
      holdings:
        type: object
        description: Opted-in ASA IDs
        example:
          "202586210": 100
          "205471981": 200
        additionalProperties: true
    example:
      address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      holdings:
        "202586210": 100
        "205471981": 200
    required:
    - address
    - holdings
  AccountTrackedAccountResponseCollection:
    title: 'Mediatype identifier: application/vnd.algodex.account; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/TrackedAccountResponse'
    description: ListResponseBody is the result type for an array of TrackedAccountResponse
      (default view)
    example:
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
  InspectUnpackRequestBody:
    title: InspectUnpackRequestBody
    type: object
    properties:
      msgpack:
        type: string
        example: Vitae nulla.
    example:
      msgpack: Exercitationem nihil tempora.
  TrackedAccountResponse:
    title: 'Mediatype identifier: application/vnd.algodex.account; view=default'
    type: object
    properties:
      address:
        type: string
        description: Public Account address
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        maxLength: 58
    description: A TrackedAccount is an Account returned by the indexer (default view)
    example:
      address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
    required:
    - address
