openapi: 3.0.3
info:
  title: AlgoDex Indexer Service
  description: Service for tracking Algorand accounts and currently opted-in Assets
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /:
    get:
      tags:
      - account
      summary: list account
      description: List all tracked accounts
      operationId: account#list
      parameters:
      - name: view
        in: query
        description: View to render
        allowEmptyValue: true
        schema:
          type: string
          description: View to render
          example: default
          enum:
          - default
          - full
        example: default
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                description: 'Response body may alternatively be #/components/schemas/TrackedAccountResponseFullCollection'
                $ref: '#/components/schemas/TrackedAccountCollection'
              example:
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                assets:
                - 202586210
                - 205471981
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                assets:
                - 202586210
                - 205471981
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                assets:
                - 202586210
                - 205471981
              - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                assets:
                - 202586210
                - 205471981
    post:
      tags:
      - account
      summary: add account
      description: Add Algorand account to track
      operationId: account#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example: Cupiditate totam eum expedita ut illum.
            example: Vitae nulla.
      responses:
        "200":
          description: OK response.
  /{address}:
    get:
      tags:
      - account
      summary: get account
      description: Get specific account
      operationId: account#get
      parameters:
      - name: address
        in: path
        description: Public Account address
        required: true
        schema:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              example:
                address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
                assets:
                - 202586210
                - 205471981
  /openapi.json:
    get:
      tags:
      - account
      summary: Download ./gen/http/openapi.json
      operationId: account#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Account:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        assets:
          type: array
          items:
            type: integer
            example: 9352604032316809151
          description: Opted-in ASA IDs
          example:
          - 202586210
          - 205471981
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      required:
      - address
      - assets
    AlgodexAccount:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        assets:
          type: array
          items:
            type: integer
            example: 16048254601123198924
          description: Opted-in ASA IDs
          example:
          - 202586210
          - 205471981
      description: A TrackedAccount is an Account returned by the indexer
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      required:
      - address
      - assets
    TrackedAccountCollection:
      type: array
      items:
        $ref: '#/components/schemas/AlgodexAccount'
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
    TrackedAccountResponseFull:
      type: object
      properties:
        address:
          type: string
          description: Public Account address
          example: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
          maxLength: 58
        assets:
          type: array
          items:
            type: integer
            example: 11449247042763666452
          description: Opted-in ASA IDs
          example:
          - 202586210
          - 205471981
      description: A TrackedAccount is an Account returned by the indexer (full view)
      example:
        address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      required:
      - address
      - assets
    TrackedAccountResponseFullCollection:
      type: array
      items:
        $ref: '#/components/schemas/TrackedAccountResponseFull'
      description: ListResponseBody is the result type for an array of TrackedAccountResponse
        (full view)
      example:
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
      - address: 4F5OA5OQC5TBHMCUDJWGKMUZAQE7BGWCKSJJSJEMJO5PURIFT5RW3VHNZU
        assets:
        - 202586210
        - 205471981
tags:
- name: account
  description: The account service specifies which Algorand accounts to track
